[[midasm_hook]]  
address = 0x8291680C
name = "force_fps_display"  
jump_address_on_true = 0x82916810

[[midasm_hook]]  
address = 0x82369650
name = "force_perf_graph_display"  
jump_address_on_true = 0x82369654